# Simple workflow for deploying Angular content to GitHub Pages
name: Deploy Angular content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular Project
        # The '--output-path=docs' creates a 'docs' folder at the root of your repository
        # containing the build artifacts.
        # The '--base-href' is crucial for GitHub Pages. Replace 'your-repo-name'
        # with the actual name of your GitHub repository (e.g., if your URL is
        # https://username.github.io/my-angular-app/, then your repo name is 'my-angular-app').
        run: npm run build -- --output-path=docs --base-href=/${{ github.event.repository.name }}/

      # --- NEW VERIFICATION STEP ---
      - name: Verify build output
        run: |
          echo "Listing contents of the 'docs' directory:"
          ls -R docs
          echo "Checking for index.html in docs/"
          if [ -f docs/index.html ]; then
            echo "index.html found in docs/!"
          else
            echo "WARNING: index.html NOT found in docs/. Your Angular build might not be outputting correctly."
            exit 1 # Fail the workflow if index.html is missing
          fi
      # --- END VERIFICATION STEP ---

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This path must point to the directory containing your built Angular application's index.html
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
